name = "turbomart"
compatibility_date = "2025-03-25"

# Configure Cloudflare Pages
[site]
bucket = "./public"

# Configure Workers Routes
[routes]
pattern = "/*"
script = "index.js"

# Configure Environment Variables
[vars]
NODE_ENV = "production"

# Configure KV Namespace for caching
[[kv_namespaces]]
binding = "TURBOMART_CACHE"
id = "$CLOUDFLARE_KV_NAMESPACE_ID" # Will be replaced with actual KV namespace ID from environment variables

# Configure R2 Bucket for image storage
[[r2_buckets]]
binding = "TURBOMART_IMAGES"
bucket_name = "turbomart-images"
preview_bucket_name = "turbomart-images-dev" 