#!/bin/bash

DB_URL="$(cat .env.local | grep COCKROACH_DB_URL | cut -d '=' -f2-)"

echo "Starting import of all batches..."

echo "Importing batch 0..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.0
echo "Importing batch 1..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.1
echo "Importing batch 2..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.2
echo "Importing batch 3..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.3
echo "Importing batch 4..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.4
echo "Importing batch 5..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.5
echo "Importing batch 6..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.6
echo "Importing batch 7..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.7
echo "Importing batch 8..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.8
echo "Importing batch 9..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.9
echo "Importing batch 10..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.10
echo "Importing batch 11..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.11
echo "Importing batch 12..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.12
echo "Importing batch 13..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.13
echo "Importing batch 14..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.14
echo "Importing batch 15..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.15
echo "Importing batch 16..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.16
echo "Importing batch 17..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.17
echo "Importing batch 18..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.18
echo "Importing batch 19..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.19
echo "Importing batch 20..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.20
echo "Importing batch 21..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.21
echo "Importing batch 22..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.22
echo "Importing batch 23..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.23
echo "Importing batch 24..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.24
echo "Importing batch 25..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.25
echo "Importing batch 26..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.26
echo "Importing batch 27..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.27
echo "Importing batch 28..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.28
echo "Importing batch 29..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.29
echo "Importing batch 30..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.30
echo "Importing batch 31..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.31
echo "Importing batch 32..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.32
echo "Importing batch 33..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.33
echo "Importing batch 34..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.34
echo "Importing batch 35..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.35
echo "Importing batch 36..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.36
echo "Importing batch 37..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.37
echo "Importing batch 38..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.38
echo "Importing batch 39..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.39
echo "Importing batch 40..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.40
echo "Importing batch 41..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.41
echo "Importing batch 42..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.42
echo "Importing batch 43..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.43
echo "Importing batch 44..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.44
echo "Importing batch 45..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.45
echo "Importing batch 46..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.46
echo "Importing batch 47..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.47
echo "Importing batch 48..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.48
echo "Importing batch 49..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.49
echo "Importing batch 50..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.50
echo "Importing batch 51..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.51
echo "Importing batch 52..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.52
echo "Importing batch 53..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.53
echo "Importing batch 54..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.54
echo "Importing batch 55..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.55
echo "Importing batch 56..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.56
echo "Importing batch 57..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.57
echo "Importing batch 58..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.58
echo "Importing batch 59..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.59
echo "Importing batch 60..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.60
echo "Importing batch 61..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.61
echo "Importing batch 62..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.62
echo "Importing batch 63..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.63
echo "Importing batch 64..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.64
echo "Importing batch 65..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.65
echo "Importing batch 66..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.66
echo "Importing batch 67..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.67
echo "Importing batch 68..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.68
echo "Importing batch 69..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.69
echo "Importing batch 70..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.70
echo "Importing batch 71..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.71
echo "Importing batch 72..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.72
echo "Importing batch 73..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.73
echo "Importing batch 74..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.74
echo "Importing batch 75..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.75
echo "Importing batch 76..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.76
echo "Importing batch 77..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.77
echo "Importing batch 78..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.78
echo "Importing batch 79..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.79
echo "Importing batch 80..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.80
echo "Importing batch 81..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.81
echo "Importing batch 82..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.82
echo "Importing batch 83..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.83
echo "Importing batch 84..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.84
echo "Importing batch 85..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.85
echo "Importing batch 86..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.86
echo "Importing batch 87..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.87
echo "Importing batch 88..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.88
echo "Importing batch 89..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.89
echo "Importing batch 90..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.90
echo "Importing batch 91..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.91
echo "Importing batch 92..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.92
echo "Importing batch 93..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.93
echo "Importing batch 94..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.94
echo "Importing batch 95..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.95
echo "Importing batch 96..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.96
echo "Importing batch 97..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.97
echo "Importing batch 98..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.98
echo "Importing batch 99..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.99
echo "Importing batch 100..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.100
echo "Importing batch 101..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.101
echo "Importing batch 102..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.102
echo "Importing batch 103..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.103
echo "Importing batch 104..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.104
echo "Importing batch 105..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.105
echo "Importing batch 106..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.106
echo "Importing batch 107..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.107
echo "Importing batch 108..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.108
echo "Importing batch 109..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.109
echo "Importing batch 110..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.110
echo "Importing batch 111..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.111
echo "Importing batch 112..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.112
echo "Importing batch 113..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.113
echo "Importing batch 114..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.114
echo "Importing batch 115..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.115
echo "Importing batch 116..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.116
echo "Importing batch 117..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.117
echo "Importing batch 118..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.118
echo "Importing batch 119..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.119
echo "Importing batch 120..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.120
echo "Importing batch 121..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.121
echo "Importing batch 122..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.122
echo "Importing batch 123..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.123
echo "Importing batch 124..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.124
echo "Importing batch 125..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.125
echo "Importing batch 126..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.126
echo "Importing batch 127..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.127
echo "Importing batch 128..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.128
echo "Importing batch 129..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.129
echo "Importing batch 130..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.130
echo "Importing batch 131..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.131
echo "Importing batch 132..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.132
echo "Importing batch 133..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.133
echo "Importing batch 134..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.134
echo "Importing batch 135..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.135
echo "Importing batch 136..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.136
echo "Importing batch 137..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.137
echo "Importing batch 138..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.138
echo "Importing batch 139..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.139
echo "Importing batch 140..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.140
echo "Importing batch 141..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.141
echo "Importing batch 142..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.142
echo "Importing batch 143..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.143
echo "Importing batch 144..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.144
echo "Importing batch 145..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.145
echo "Importing batch 146..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.146
echo "Importing batch 147..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.147
echo "Importing batch 148..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.148
echo "Importing batch 149..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.149
echo "Importing batch 150..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.150
echo "Importing batch 151..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.151
echo "Importing batch 152..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.152
echo "Importing batch 153..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.153
echo "Importing batch 154..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.154
echo "Importing batch 155..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.155
echo "Importing batch 156..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.156
echo "Importing batch 157..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.157
echo "Importing batch 158..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.158
echo "Importing batch 159..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.159
echo "Importing batch 160..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.160
echo "Importing batch 161..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.161
echo "Importing batch 162..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.162
echo "Importing batch 163..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.163
echo "Importing batch 164..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.164
echo "Importing batch 165..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.165
echo "Importing batch 166..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.166
echo "Importing batch 167..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.167
echo "Importing batch 168..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.168
echo "Importing batch 169..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.169
echo "Importing batch 170..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.170
echo "Importing batch 171..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.171
echo "Importing batch 172..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.172
echo "Importing batch 173..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.173
echo "Importing batch 174..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.174
echo "Importing batch 175..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.175
echo "Importing batch 176..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.176
echo "Importing batch 177..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.177
echo "Importing batch 178..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.178
echo "Importing batch 179..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.179
echo "Importing batch 180..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.180
echo "Importing batch 181..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.181
echo "Importing batch 182..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.182
echo "Importing batch 183..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.183
echo "Importing batch 184..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.184
echo "Importing batch 185..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.185
echo "Importing batch 186..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.186
echo "Importing batch 187..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.187
echo "Importing batch 188..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.188
echo "Importing batch 189..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.189
echo "Importing batch 190..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.190
echo "Importing batch 191..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.191
echo "Importing batch 192..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.192
echo "Importing batch 193..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.193
echo "Importing batch 194..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.194
echo "Importing batch 195..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.195
echo "Importing batch 196..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.196
echo "Importing batch 197..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.197
echo "Importing batch 198..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.198
echo "Importing batch 199..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.199
echo "Importing batch 200..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.200
echo "Importing batch 201..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.201
echo "Importing batch 202..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.202
echo "Importing batch 203..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.203
echo "Importing batch 204..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.204
echo "Importing batch 205..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.205
echo "Importing batch 206..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.206
echo "Importing batch 207..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.207
echo "Importing batch 208..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.208
echo "Importing batch 209..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.209
echo "Importing batch 210..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.210
echo "Importing batch 211..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.211
echo "Importing batch 212..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.212
echo "Importing batch 213..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.213
echo "Importing batch 214..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.214
echo "Importing batch 215..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.215
echo "Importing batch 216..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.216
echo "Importing batch 217..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.217
echo "Importing batch 218..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.218
echo "Importing batch 219..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.219
echo "Importing batch 220..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.220
echo "Importing batch 221..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.221
echo "Importing batch 222..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.222
echo "Importing batch 223..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.223
echo "Importing batch 224..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.224
echo "Importing batch 225..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.225
echo "Importing batch 226..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.226
echo "Importing batch 227..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.227
echo "Importing batch 228..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.228
echo "Importing batch 229..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.229
echo "Importing batch 230..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.230
echo "Importing batch 231..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.231
echo "Importing batch 232..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.232
echo "Importing batch 233..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.233
echo "Importing batch 234..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.234
echo "Importing batch 235..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.235
echo "Importing batch 236..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.236
echo "Importing batch 237..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.237
echo "Importing batch 238..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.238
echo "Importing batch 239..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.239
echo "Importing batch 240..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.240
echo "Importing batch 241..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.241
echo "Importing batch 242..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.242
echo "Importing batch 243..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.243
echo "Importing batch 244..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.244
echo "Importing batch 245..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.245
echo "Importing batch 246..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.246
echo "Importing batch 247..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.247
echo "Importing batch 248..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.248
echo "Importing batch 249..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.249
echo "Importing batch 250..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.250
echo "Importing batch 251..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.251
echo "Importing batch 252..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.252
echo "Importing batch 253..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.253
echo "Importing batch 254..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.254
echo "Importing batch 255..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.255
echo "Importing batch 256..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.256
echo "Importing batch 257..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.257
echo "Importing batch 258..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.258
echo "Importing batch 259..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.259
echo "Importing batch 260..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.260
echo "Importing batch 261..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.261
echo "Importing batch 262..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.262
echo "Importing batch 263..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.263
echo "Importing batch 264..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.264
echo "Importing batch 265..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.265
echo "Importing batch 266..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.266
echo "Importing batch 267..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.267
echo "Importing batch 268..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.268
echo "Importing batch 269..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.269
echo "Importing batch 270..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.270
echo "Importing batch 271..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.271
echo "Importing batch 272..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.272
echo "Importing batch 273..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.273
echo "Importing batch 274..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.274
echo "Importing batch 275..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.275
echo "Importing batch 276..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.276
echo "Importing batch 277..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.277
echo "Importing batch 278..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.278
echo "Importing batch 279..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.279
echo "Importing batch 280..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.280
echo "Importing batch 281..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.281
echo "Importing batch 282..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.282
echo "Importing batch 283..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.283
echo "Importing batch 284..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.284
echo "Importing batch 285..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.285
echo "Importing batch 286..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.286
echo "Importing batch 287..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.287
echo "Importing batch 288..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.288
echo "Importing batch 289..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.289
echo "Importing batch 290..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.290
echo "Importing batch 291..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.291
echo "Importing batch 292..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.292
echo "Importing batch 293..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.293
echo "Importing batch 294..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.294
echo "Importing batch 295..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.295
echo "Importing batch 296..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.296
echo "Importing batch 297..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.297
echo "Importing batch 298..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.298
echo "Importing batch 299..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.299
echo "Importing batch 300..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.300
echo "Importing batch 301..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.301
echo "Importing batch 302..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.302
echo "Importing batch 303..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.303
echo "Importing batch 304..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.304
echo "Importing batch 305..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.305
echo "Importing batch 306..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.306
echo "Importing batch 307..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.307
echo "Importing batch 308..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.308
echo "Importing batch 309..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.309
echo "Importing batch 310..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.310
echo "Importing batch 311..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.311
echo "Importing batch 312..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.312
echo "Importing batch 313..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.313
echo "Importing batch 314..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.314
echo "Importing batch 315..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.315
echo "Importing batch 316..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.316
echo "Importing batch 317..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.317
echo "Importing batch 318..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.318
echo "Importing batch 319..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.319
echo "Importing batch 320..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.320
echo "Importing batch 321..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.321
echo "Importing batch 322..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.322
echo "Importing batch 323..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.323
echo "Importing batch 324..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.324
echo "Importing batch 325..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.325
echo "Importing batch 326..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.326
echo "Importing batch 327..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.327
echo "Importing batch 328..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.328
echo "Importing batch 329..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.329
echo "Importing batch 330..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.330
echo "Importing batch 331..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.331
echo "Importing batch 332..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.332
echo "Importing batch 333..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.333
echo "Importing batch 334..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.334
echo "Importing batch 335..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.335
echo "Importing batch 336..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.336
echo "Importing batch 337..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.337
echo "Importing batch 338..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.338
echo "Importing batch 339..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.339
echo "Importing batch 340..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.340
echo "Importing batch 341..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.341
echo "Importing batch 342..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.342
echo "Importing batch 343..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.343
echo "Importing batch 344..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.344
echo "Importing batch 345..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.345
echo "Importing batch 346..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.346
echo "Importing batch 347..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.347
echo "Importing batch 348..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.348
echo "Importing batch 349..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.349
echo "Importing batch 350..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.350
echo "Importing batch 351..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.351
echo "Importing batch 352..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.352
echo "Importing batch 353..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.353
echo "Importing batch 354..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.354
echo "Importing batch 355..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.355
echo "Importing batch 356..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.356
echo "Importing batch 357..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.357
echo "Importing batch 358..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.358
echo "Importing batch 359..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.359
echo "Importing batch 360..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.360
echo "Importing batch 361..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.361
echo "Importing batch 362..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.362
echo "Importing batch 363..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.363
echo "Importing batch 364..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.364
echo "Importing batch 365..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.365
echo "Importing batch 366..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.366
echo "Importing batch 367..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.367
echo "Importing batch 368..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.368
echo "Importing batch 369..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.369
echo "Importing batch 370..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.370
echo "Importing batch 371..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.371
echo "Importing batch 372..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.372
echo "Importing batch 373..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.373
echo "Importing batch 374..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.374
echo "Importing batch 375..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.375
echo "Importing batch 376..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.376
echo "Importing batch 377..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.377
echo "Importing batch 378..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.378
echo "Importing batch 379..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.379
echo "Importing batch 380..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.380
echo "Importing batch 381..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.381
echo "Importing batch 382..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.382
echo "Importing batch 383..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.383
echo "Importing batch 384..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.384
echo "Importing batch 385..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.385
echo "Importing batch 386..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.386
echo "Importing batch 387..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.387
echo "Importing batch 388..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.388
echo "Importing batch 389..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.389
echo "Importing batch 390..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.390
echo "Importing batch 391..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.391
echo "Importing batch 392..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.392
echo "Importing batch 393..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.393
echo "Importing batch 394..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.394
echo "Importing batch 395..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.395
echo "Importing batch 396..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.396
echo "Importing batch 397..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.397
echo "Importing batch 398..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.398
echo "Importing batch 399..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.399
echo "Importing batch 400..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.400
echo "Importing batch 401..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.401
echo "Importing batch 402..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.402
echo "Importing batch 403..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.403
echo "Importing batch 404..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.404
echo "Importing batch 405..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.405
echo "Importing batch 406..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.406
echo "Importing batch 407..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.407
echo "Importing batch 408..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.408
echo "Importing batch 409..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.409
echo "Importing batch 410..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.410
echo "Importing batch 411..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.411
echo "Importing batch 412..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.412
echo "Importing batch 413..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.413
echo "Importing batch 414..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.414
echo "Importing batch 415..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.415
echo "Importing batch 416..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.416
echo "Importing batch 417..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.417
echo "Importing batch 418..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.418
echo "Importing batch 419..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.419
echo "Importing batch 420..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.420
echo "Importing batch 421..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.421
echo "Importing batch 422..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.422
echo "Importing batch 423..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.423
echo "Importing batch 424..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.424
echo "Importing batch 425..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.425
echo "Importing batch 426..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.426
echo "Importing batch 427..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.427
echo "Importing batch 428..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.428
echo "Importing batch 429..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.429
echo "Importing batch 430..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.430
echo "Importing batch 431..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.431
echo "Importing batch 432..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.432
echo "Importing batch 433..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.433
echo "Importing batch 434..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.434
echo "Importing batch 435..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.435
echo "Importing batch 436..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.436
echo "Importing batch 437..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.437
echo "Importing batch 438..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.438
echo "Importing batch 439..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.439
echo "Importing batch 440..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.440
echo "Importing batch 441..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.441
echo "Importing batch 442..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.442
echo "Importing batch 443..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.443
echo "Importing batch 444..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.444
echo "Importing batch 445..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.445
echo "Importing batch 446..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.446
echo "Importing batch 447..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.447
echo "Importing batch 448..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.448
echo "Importing batch 449..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.449
echo "Importing batch 450..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.450
echo "Importing batch 451..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.451
echo "Importing batch 452..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.452
echo "Importing batch 453..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.453
echo "Importing batch 454..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.454
echo "Importing batch 455..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.455
echo "Importing batch 456..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.456
echo "Importing batch 457..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.457
echo "Importing batch 458..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.458
echo "Importing batch 459..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.459
echo "Importing batch 460..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.460
echo "Importing batch 461..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.461
echo "Importing batch 462..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.462
echo "Importing batch 463..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.463
echo "Importing batch 464..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.464
echo "Importing batch 465..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.465
echo "Importing batch 466..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.466
echo "Importing batch 467..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.467
echo "Importing batch 468..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.468
echo "Importing batch 469..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.469
echo "Importing batch 470..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.470
echo "Importing batch 471..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.471
echo "Importing batch 472..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.472
echo "Importing batch 473..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.473
echo "Importing batch 474..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.474
echo "Importing batch 475..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.475
echo "Importing batch 476..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.476
echo "Importing batch 477..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.477
echo "Importing batch 478..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.478
echo "Importing batch 479..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.479
echo "Importing batch 480..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.480
echo "Importing batch 481..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.481
echo "Importing batch 482..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.482
echo "Importing batch 483..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.483
echo "Importing batch 484..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.484
echo "Importing batch 485..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.485
echo "Importing batch 486..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.486
echo "Importing batch 487..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.487
echo "Importing batch 488..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.488
echo "Importing batch 489..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.489
echo "Importing batch 490..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.490
echo "Importing batch 491..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.491
echo "Importing batch 492..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.492
echo "Importing batch 493..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.493
echo "Importing batch 494..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.494
echo "Importing batch 495..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.495
echo "Importing batch 496..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.496
echo "Importing batch 497..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.497
echo "Importing batch 498..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.498
echo "Importing batch 499..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.499
echo "Importing batch 500..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.500
echo "Importing batch 501..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.501
echo "Importing batch 502..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.502
echo "Importing batch 503..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.503
echo "Importing batch 504..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.504
echo "Importing batch 505..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.505
echo "Importing batch 506..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.506
echo "Importing batch 507..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.507
echo "Importing batch 508..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.508
echo "Importing batch 509..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.509
echo "Importing batch 510..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.510
echo "Importing batch 511..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.511
echo "Importing batch 512..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.512
echo "Importing batch 513..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.513
echo "Importing batch 514..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.514
echo "Importing batch 515..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.515
echo "Importing batch 516..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.516
echo "Importing batch 517..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.517
echo "Importing batch 518..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.518
echo "Importing batch 519..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.519
echo "Importing batch 520..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.520
echo "Importing batch 521..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.521
echo "Importing batch 522..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.522
echo "Importing batch 523..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.523
echo "Importing batch 524..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.524
echo "Importing batch 525..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.525
echo "Importing batch 526..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.526
echo "Importing batch 527..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.527
echo "Importing batch 528..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.528
echo "Importing batch 529..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.529
echo "Importing batch 530..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.530
echo "Importing batch 531..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.531
echo "Importing batch 532..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.532
echo "Importing batch 533..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.533
echo "Importing batch 534..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.534
echo "Importing batch 535..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.535
echo "Importing batch 536..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.536
echo "Importing batch 537..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.537
echo "Importing batch 538..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.538
echo "Importing batch 539..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.539
echo "Importing batch 540..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.540
echo "Importing batch 541..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.541
echo "Importing batch 542..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.542
echo "Importing batch 543..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.543
echo "Importing batch 544..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.544
echo "Importing batch 545..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.545
echo "Importing batch 546..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.546
echo "Importing batch 547..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.547
echo "Importing batch 548..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.548
echo "Importing batch 549..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.549
echo "Importing batch 550..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.550
echo "Importing batch 551..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.551
echo "Importing batch 552..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.552
echo "Importing batch 553..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.553
echo "Importing batch 554..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.554
echo "Importing batch 555..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.555
echo "Importing batch 556..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.556
echo "Importing batch 557..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.557
echo "Importing batch 558..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.558
echo "Importing batch 559..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.559
echo "Importing batch 560..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.560
echo "Importing batch 561..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.561
echo "Importing batch 562..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.562
echo "Importing batch 563..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.563
echo "Importing batch 564..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.564
echo "Importing batch 565..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.565
echo "Importing batch 566..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.566
echo "Importing batch 567..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.567
echo "Importing batch 568..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.568
echo "Importing batch 569..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.569
echo "Importing batch 570..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.570
echo "Importing batch 571..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.571
echo "Importing batch 572..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.572
echo "Importing batch 573..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.573
echo "Importing batch 574..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.574
echo "Importing batch 575..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.575
echo "Importing batch 576..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.576
echo "Importing batch 577..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.577
echo "Importing batch 578..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.578
echo "Importing batch 579..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.579
echo "Importing batch 580..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.580
echo "Importing batch 581..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.581
echo "Importing batch 582..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.582
echo "Importing batch 583..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.583
echo "Importing batch 584..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.584
echo "Importing batch 585..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.585
echo "Importing batch 586..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.586
echo "Importing batch 587..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.587
echo "Importing batch 588..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.588
echo "Importing batch 589..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.589
echo "Importing batch 590..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.590
echo "Importing batch 591..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.591
echo "Importing batch 592..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.592
echo "Importing batch 593..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.593
echo "Importing batch 594..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.594
echo "Importing batch 595..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.595
echo "Importing batch 596..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.596
echo "Importing batch 597..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.597
echo "Importing batch 598..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.598
echo "Importing batch 599..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.599
echo "Importing batch 600..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.600
echo "Importing batch 601..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.601
echo "Importing batch 602..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.602
echo "Importing batch 603..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.603
echo "Importing batch 604..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.604
echo "Importing batch 605..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.605
echo "Importing batch 606..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.606
echo "Importing batch 607..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.607
echo "Importing batch 608..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.608
echo "Importing batch 609..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.609
echo "Importing batch 610..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.610
echo "Importing batch 611..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.611
echo "Importing batch 612..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.612
echo "Importing batch 613..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.613
echo "Importing batch 614..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.614
echo "Importing batch 615..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.615
echo "Importing batch 616..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.616
echo "Importing batch 617..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.617
echo "Importing batch 618..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.618
echo "Importing batch 619..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.619
echo "Importing batch 620..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.620
echo "Importing batch 621..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.621
echo "Importing batch 622..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.622
echo "Importing batch 623..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.623
echo "Importing batch 624..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.624
echo "Importing batch 625..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.625
echo "Importing batch 626..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.626
echo "Importing batch 627..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.627
echo "Importing batch 628..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.628
echo "Importing batch 629..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.629
echo "Importing batch 630..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.630
echo "Importing batch 631..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.631
echo "Importing batch 632..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.632
echo "Importing batch 633..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.633
echo "Importing batch 634..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.634
echo "Importing batch 635..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.635
echo "Importing batch 636..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.636
echo "Importing batch 637..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.637
echo "Importing batch 638..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.638
echo "Importing batch 639..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.639
echo "Importing batch 640..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.640
echo "Importing batch 641..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.641
echo "Importing batch 642..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.642
echo "Importing batch 643..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.643
echo "Importing batch 644..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.644
echo "Importing batch 645..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.645
echo "Importing batch 646..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.646
echo "Importing batch 647..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.647
echo "Importing batch 648..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.648
echo "Importing batch 649..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.649
echo "Importing batch 650..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.650
echo "Importing batch 651..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.651
echo "Importing batch 652..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.652
echo "Importing batch 653..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.653
echo "Importing batch 654..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.654
echo "Importing batch 655..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.655
echo "Importing batch 656..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.656
echo "Importing batch 657..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.657
echo "Importing batch 658..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.658
echo "Importing batch 659..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.659
echo "Importing batch 660..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.660
echo "Importing batch 661..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.661
echo "Importing batch 662..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.662
echo "Importing batch 663..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.663
echo "Importing batch 664..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.664
echo "Importing batch 665..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.665
echo "Importing batch 666..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.666
echo "Importing batch 667..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.667
echo "Importing batch 668..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.668
echo "Importing batch 669..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.669
echo "Importing batch 670..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.670
echo "Importing batch 671..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.671
echo "Importing batch 672..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.672
echo "Importing batch 673..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.673
echo "Importing batch 674..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.674
echo "Importing batch 675..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.675
echo "Importing batch 676..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.676
echo "Importing batch 677..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.677
echo "Importing batch 678..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.678
echo "Importing batch 679..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.679
echo "Importing batch 680..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.680
echo "Importing batch 681..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.681
echo "Importing batch 682..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.682
echo "Importing batch 683..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.683
echo "Importing batch 684..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.684
echo "Importing batch 685..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.685
echo "Importing batch 686..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.686
echo "Importing batch 687..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.687
echo "Importing batch 688..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.688
echo "Importing batch 689..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.689
echo "Importing batch 690..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.690
echo "Importing batch 691..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.691
echo "Importing batch 692..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.692
echo "Importing batch 693..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.693
echo "Importing batch 694..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.694
echo "Importing batch 695..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.695
echo "Importing batch 696..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.696
echo "Importing batch 697..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.697
echo "Importing batch 698..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.698
echo "Importing batch 699..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.699
echo "Importing batch 700..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.700
echo "Importing batch 701..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.701
echo "Importing batch 702..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.702
echo "Importing batch 703..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.703
echo "Importing batch 704..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.704
echo "Importing batch 705..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.705
echo "Importing batch 706..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.706
echo "Importing batch 707..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.707
echo "Importing batch 708..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.708
echo "Importing batch 709..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.709
echo "Importing batch 710..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.710
echo "Importing batch 711..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.711
echo "Importing batch 712..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.712
echo "Importing batch 713..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.713
echo "Importing batch 714..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.714
echo "Importing batch 715..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.715
echo "Importing batch 716..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.716
echo "Importing batch 717..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.717
echo "Importing batch 718..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.718
echo "Importing batch 719..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.719
echo "Importing batch 720..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.720
echo "Importing batch 721..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.721
echo "Importing batch 722..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.722
echo "Importing batch 723..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.723
echo "Importing batch 724..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.724
echo "Importing batch 725..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.725
echo "Importing batch 726..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.726
echo "Importing batch 727..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.727
echo "Importing batch 728..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.728
echo "Importing batch 729..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.729
echo "Importing batch 730..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.730
echo "Importing batch 731..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.731
echo "Importing batch 732..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.732
echo "Importing batch 733..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.733
echo "Importing batch 734..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.734
echo "Importing batch 735..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.735
echo "Importing batch 736..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.736
echo "Importing batch 737..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.737
echo "Importing batch 738..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.738
echo "Importing batch 739..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.739
echo "Importing batch 740..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.740
echo "Importing batch 741..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.741
echo "Importing batch 742..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.742
echo "Importing batch 743..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.743
echo "Importing batch 744..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.744
echo "Importing batch 745..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.745
echo "Importing batch 746..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.746
echo "Importing batch 747..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.747
echo "Importing batch 748..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.748
echo "Importing batch 749..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.749
echo "Importing batch 750..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.750
echo "Importing batch 751..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.751
echo "Importing batch 752..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.752
echo "Importing batch 753..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.753
echo "Importing batch 754..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.754
echo "Importing batch 755..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.755
echo "Importing batch 756..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.756
echo "Importing batch 757..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.757
echo "Importing batch 758..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.758
echo "Importing batch 759..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.759
echo "Importing batch 760..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.760
echo "Importing batch 761..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.761
echo "Importing batch 762..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.762
echo "Importing batch 763..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.763
echo "Importing batch 764..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.764
echo "Importing batch 765..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.765
echo "Importing batch 766..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.766
echo "Importing batch 767..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.767
echo "Importing batch 768..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.768
echo "Importing batch 769..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.769
echo "Importing batch 770..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.770
echo "Importing batch 771..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.771
echo "Importing batch 772..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.772
echo "Importing batch 773..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.773
echo "Importing batch 774..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.774
echo "Importing batch 775..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.775
echo "Importing batch 776..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.776
echo "Importing batch 777..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.777
echo "Importing batch 778..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.778
echo "Importing batch 779..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.779
echo "Importing batch 780..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.780
echo "Importing batch 781..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.781
echo "Importing batch 782..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.782
echo "Importing batch 783..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.783
echo "Importing batch 784..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.784
echo "Importing batch 785..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.785
echo "Importing batch 786..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.786
echo "Importing batch 787..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.787
echo "Importing batch 788..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.788
echo "Importing batch 789..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.789
echo "Importing batch 790..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.790
echo "Importing batch 791..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.791
echo "Importing batch 792..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.792
echo "Importing batch 793..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.793
echo "Importing batch 794..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.794
echo "Importing batch 795..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.795
echo "Importing batch 796..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.796
echo "Importing batch 797..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.797
echo "Importing batch 798..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.798
echo "Importing batch 799..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.799
echo "Importing batch 800..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.800
echo "Importing batch 801..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.801
echo "Importing batch 802..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.802
echo "Importing batch 803..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.803
echo "Importing batch 804..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.804
echo "Importing batch 805..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.805
echo "Importing batch 806..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.806
echo "Importing batch 807..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.807
echo "Importing batch 808..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.808
echo "Importing batch 809..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.809
echo "Importing batch 810..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.810
echo "Importing batch 811..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.811
echo "Importing batch 812..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.812
echo "Importing batch 813..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.813
echo "Importing batch 814..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.814
echo "Importing batch 815..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.815
echo "Importing batch 816..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.816
echo "Importing batch 817..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.817
echo "Importing batch 818..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.818
echo "Importing batch 819..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.819
echo "Importing batch 820..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.820
echo "Importing batch 821..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.821
echo "Importing batch 822..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.822
echo "Importing batch 823..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.823
echo "Importing batch 824..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.824
echo "Importing batch 825..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.825
echo "Importing batch 826..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.826
echo "Importing batch 827..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.827
echo "Importing batch 828..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.828
echo "Importing batch 829..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.829
echo "Importing batch 830..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.830
echo "Importing batch 831..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.831
echo "Importing batch 832..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.832
echo "Importing batch 833..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.833
echo "Importing batch 834..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.834
echo "Importing batch 835..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.835
echo "Importing batch 836..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.836
echo "Importing batch 837..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.837
echo "Importing batch 838..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.838
echo "Importing batch 839..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.839
echo "Importing batch 840..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.840
echo "Importing batch 841..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.841
echo "Importing batch 842..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.842
echo "Importing batch 843..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.843
echo "Importing batch 844..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.844
echo "Importing batch 845..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.845
echo "Importing batch 846..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.846
echo "Importing batch 847..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.847
echo "Importing batch 848..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.848
echo "Importing batch 849..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.849
echo "Importing batch 850..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.850
echo "Importing batch 851..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.851
echo "Importing batch 852..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.852
echo "Importing batch 853..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.853
echo "Importing batch 854..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.854
echo "Importing batch 855..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.855
echo "Importing batch 856..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.856
echo "Importing batch 857..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.857
echo "Importing batch 858..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.858
echo "Importing batch 859..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.859
echo "Importing batch 860..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.860
echo "Importing batch 861..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.861
echo "Importing batch 862..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.862
echo "Importing batch 863..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.863
echo "Importing batch 864..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.864
echo "Importing batch 865..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.865
echo "Importing batch 866..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.866
echo "Importing batch 867..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.867
echo "Importing batch 868..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.868
echo "Importing batch 869..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.869
echo "Importing batch 870..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.870
echo "Importing batch 871..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.871
echo "Importing batch 872..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.872
echo "Importing batch 873..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.873
echo "Importing batch 874..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.874
echo "Importing batch 875..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.875
echo "Importing batch 876..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.876
echo "Importing batch 877..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.877
echo "Importing batch 878..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.878
echo "Importing batch 879..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.879
echo "Importing batch 880..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.880
echo "Importing batch 881..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.881
echo "Importing batch 882..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.882
echo "Importing batch 883..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.883
echo "Importing batch 884..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.884
echo "Importing batch 885..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.885
echo "Importing batch 886..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.886
echo "Importing batch 887..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.887
echo "Importing batch 888..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.888
echo "Importing batch 889..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.889
echo "Importing batch 890..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.890
echo "Importing batch 891..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.891
echo "Importing batch 892..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.892
echo "Importing batch 893..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.893
echo "Importing batch 894..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.894
echo "Importing batch 895..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.895
echo "Importing batch 896..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.896
echo "Importing batch 897..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.897
echo "Importing batch 898..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.898
echo "Importing batch 899..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.899
echo "Importing batch 900..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.900
echo "Importing batch 901..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.901
echo "Importing batch 902..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.902
echo "Importing batch 903..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.903
echo "Importing batch 904..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.904
echo "Importing batch 905..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.905
echo "Importing batch 906..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.906
echo "Importing batch 907..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.907
echo "Importing batch 908..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.908
echo "Importing batch 909..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.909
echo "Importing batch 910..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.910
echo "Importing batch 911..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.911
echo "Importing batch 912..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.912
echo "Importing batch 913..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.913
echo "Importing batch 914..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.914
echo "Importing batch 915..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.915
echo "Importing batch 916..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.916
echo "Importing batch 917..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.917
echo "Importing batch 918..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.918
echo "Importing batch 919..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.919
echo "Importing batch 920..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.920
echo "Importing batch 921..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.921
echo "Importing batch 922..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.922
echo "Importing batch 923..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.923
echo "Importing batch 924..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.924
echo "Importing batch 925..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.925
echo "Importing batch 926..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.926
echo "Importing batch 927..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.927
echo "Importing batch 928..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.928
echo "Importing batch 929..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.929
echo "Importing batch 930..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.930
echo "Importing batch 931..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.931
echo "Importing batch 932..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.932
echo "Importing batch 933..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.933
echo "Importing batch 934..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.934
echo "Importing batch 935..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.935
echo "Importing batch 936..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.936
echo "Importing batch 937..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.937
echo "Importing batch 938..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.938
echo "Importing batch 939..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.939
echo "Importing batch 940..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.940
echo "Importing batch 941..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.941
echo "Importing batch 942..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.942
echo "Importing batch 943..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.943
echo "Importing batch 944..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.944
echo "Importing batch 945..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.945
echo "Importing batch 946..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.946
echo "Importing batch 947..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.947
echo "Importing batch 948..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.948
echo "Importing batch 949..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.949
echo "Importing batch 950..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.950
echo "Importing batch 951..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.951
echo "Importing batch 952..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.952
echo "Importing batch 953..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.953
echo "Importing batch 954..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.954
echo "Importing batch 955..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.955
echo "Importing batch 956..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.956
echo "Importing batch 957..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.957
echo "Importing batch 958..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.958
echo "Importing batch 959..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.959
echo "Importing batch 960..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.960
echo "Importing batch 961..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.961
echo "Importing batch 962..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.962
echo "Importing batch 963..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.963
echo "Importing batch 964..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.964
echo "Importing batch 965..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.965
echo "Importing batch 966..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.966
echo "Importing batch 967..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.967
echo "Importing batch 968..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.968
echo "Importing batch 969..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.969
echo "Importing batch 970..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.970
echo "Importing batch 971..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.971
echo "Importing batch 972..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.972
echo "Importing batch 973..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.973
echo "Importing batch 974..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.974
echo "Importing batch 975..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.975
echo "Importing batch 976..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.976
echo "Importing batch 977..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.977
echo "Importing batch 978..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.978
echo "Importing batch 979..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.979
echo "Importing batch 980..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.980
echo "Importing batch 981..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.981
echo "Importing batch 982..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.982
echo "Importing batch 983..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.983
echo "Importing batch 984..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.984
echo "Importing batch 985..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.985
echo "Importing batch 986..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.986
echo "Importing batch 987..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.987
echo "Importing batch 988..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.988
echo "Importing batch 989..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.989
echo "Importing batch 990..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.990
echo "Importing batch 991..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.991
echo "Importing batch 992..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.992
echo "Importing batch 993..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.993
echo "Importing batch 994..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.994
echo "Importing batch 995..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.995
echo "Importing batch 996..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.996
echo "Importing batch 997..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.997
echo "Importing batch 998..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.998
echo "Importing batch 999..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.999
echo "Importing batch 1000..."
psql "$DB_URL" -f data/cockroach-import-all.sql.batch.1000

echo "Import complete!"
